on:
  push:
    branches:
      - authentication
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: front-zeeven    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'                # set this to the node version to use

permissions:
  contents: read

jobs:

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          tags: front-zeeven:latest
      - name: Inspect
        run: |
          docker image inspect myimage:latest

